apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicemarket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicemarket
  template:
    metadata:
      labels:
        app: servicemarket
    spec:
      containers:
        - name: servicemarket
          image:  gcr.io/acoustic-atom-452113-j8/servicemarket:v1
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          imagePullPolicy: Always
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/db"
---
apiVersion: v1
kind: Service
metadata:
  name: servicemarket
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: servicemarket
