apiVersion: apps/v1
kind: Deployment
metadata:
  name: senderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: senderservice
  template:
    metadata:
      labels:
        app: senderservice
    spec:
      containers:
        - name: senderservice
          image: gcr.io/acoustic-atom-452113-j8/senderservice:v1
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          imagePullPolicy: Always
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: senderservice
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: senderservice
