# rabbitmq/docker-compose.yml
version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # Port do zarządzania przez HTTP
      - "5672:5672"    # Port do komunikacji AMQP
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge